### ISSUE TITLE
config_plugin attribute is not accepted

### ISSUE THREAD

**Issue by johannessen** [rjbs/Dist-Zilla-Plugin-TaskWeaver#4]
When I use a custom PodWeaver config like this:
```ini
[TaskWeaver]
config_plugin = @Author::AJNN
```
The build fails with this error message:
```
Attribute (config_plugins) does not pass the type constraint because: Validation failed for 'ArrayRef[Str]' with value @Author::AJNN at …/Moose/Object.pm line 24
```

This looks like the issue earlier described in PR #3.
https://github.com/rjbs/Dist-Zilla-Plugin-TaskWeaver/blob/04e93c87d3b3f3c6c840891dfba55a79b232555a/lib/Dist/Zilla/Plugin/TaskWeaver.pm#L6-L7

Instead of only excluding `mvp_aliases` from those roles, `mvp_multivalue_args` needs to be excluded as well. However, I don’t know how to exclude multiple methods from Moose roles (or if that’s even possible).

Adding a method that simply passes `mvp_multivalue_args` through to PodWeaver fixes the issue on my system:
```perl
sub mvp_multivalue_args {
  my ($self) = @_;

  return $self->SUPER::mvp_multivalue_args;
}
```

Should I open a new PR for this change?

**Comment by rjbs** [comment]
I've gone ahead and added the multiple exclusion, which you do with arrayrefs.  Give it a look?  Anyway, I _think_ this will help and am releasing it.  Thanks for the report!

**Comment by johannessen** [comment]
Arrayrefs – of course.

Thanks for addressing this! The new version works fine for me.

**Comment by rjbs** [comment]
Glad to do it, sorry it took so long!  Happy hacking!
